<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVySBhDr\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVySBhDr/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerVySBhDr.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerVySBhDr\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerVySBhDr\App_KernelTestDebugContainer([
    'container.build_hash' => 'VySBhDr',
    'container.build_id' => '17a8380a',
    'container.build_time' => 1714402152,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVySBhDr');
